spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
  #允许循环依赖
  main:
    allow-circular-references: true



  redis:
    host: localhost
    port: 6379





mybatis-plus:
  type-aliases-package: com.tao.springboot.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8888
